# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT30th-4th-Seminar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOPT30th-4th-Seminar
  pod 'Alamofire'
end
